### ISSUE TITLE
Users can mint many nfts

### ISSUE THREAD

**Issue by vimwitch** [semaphore-protocol/taz-apps#19]
In the [mint](https://github.com/semaphore-protocol/taz-apps/blob/main/apps/contracts/contracts/TazToken.sol#L63) function we accept a zk proof and verify it against the semaphore root. This allows a single user to make many proofs using the same identity.

I think we should limit the number of tokens that can be minted to 1 per semaphore identity. Since we're burning these semaphore identities after this event we could accept a simple proof of ownership for an identity commitment. Then we add the commitment to a list indicating it has claimed a token.

**Comment by cedoor** [comment]
@vimwitch that mint function is only used to save 9-canvas pictures, the owner is the TAZ contract itself. Since the proof verification for each specific canvas happens off-chain, I think we can use that function without any on-chain proof verification.

I think it's also ok to show two different ways to verify proofs: off-chain and on-chain.
